---
# tasks file for ec2
- ec2:
    key_name: oct-mum
    instance_type: t2.micro
    image: ami-026669ec456129a70
    wait: yes
    group: launch-wizard-1
    count: 1
    vpc_subnet_id: subnet-8387f9cf
    region: ap-south-1	
